"""add video, planta_pdf, galeria to property

Revision ID: c4f7e0870cb1
Revises: 
Create Date: 2025-11-18 22:23:10.489064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f7e0870cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('planta_pdf', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('galeria', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('galeria')
        batch_op.drop_column('planta_pdf')
        batch_op.drop_column('video')

    # ### end Alembic commands ###
